# Generated by Django 4.2.10 on 2026-03-03 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_remove_location_created_at_location_is_depot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Machine'},
        ),
        migrations.AlterField(
            model_name='location',
            name='is_depot',
            field=models.BooleanField(default=False, help_text='Define se o local é um ponto de origem/retorno (Sede, Silo, etc).'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='capacity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='machine',
            name='fuel_consumption_lh',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumo (L/h)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='operation_type',
            field=models.CharField(choices=[('harvest', 'Colheita'), ('transport', 'Transporte'), ('spraying', 'Pulverização')], default='harvest', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='speed_kmh',
            field=models.FloatField(help_text='Velocidade média operacional para cálculo de tempo de rota.', validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
